### ISSUE TITLE
Unexpected token at line 1: "�", when parsing J2735_201603

### ISSUE THREAD

**Issue by Yufei-Yan** [vlm/asn1c#171]
Hi,

it always says: 
```
Unexpected token at line 1: "�"
ASN.1 grammar parse error near line 1 (token "�"): syntax error, unexpected $end, expecting TOK_typereference or TOK_capitalreference
Cannot parse "J2735_201603DA.ASN"
```

When parsing SAE J2735_201603.

I trid to delete first several lines, which are comments, but it still gave a such error.

What could be wrong?  

Please help. 
Thank you.

**Comment by brchiu** [comment]
hi @Yufei-Yan, 

It is a so called BOM (byte order mark) at head of file, which indicates some encoding information of this text file. 

https://en.m.wikipedia.org/wiki/Byte_order_mark

You can use hex-editing capable editor, for example Ultra-editor on Windows or bless hex editor on Ubuntu, to view your J2735_201603.asn in hex mode. Then remove the heading BOM characters if any.

@leisun124 removed these BOM characters by using 'dd' utility program in Linux.

**Comment by DavidKelleySCSC** [comment]
hi @Yufei-Yan,
brchiu is right about the meaning of the code, but I do not think the original source document has that in it. I will check the master copy Monday and post back (I am the keeper/editors of the document).  Depending on what you are doing, you may want to be paranoid to confirm you have the real honest standard without further edits.  There is also an MD5 value for it but I need to look up the hash as well and will post that as well.

**Comment by Yufei-Yan** [comment]
Hi, @DavidKelleySCSC,
I got the file from my colleague. I guess he viewed the document in his operating system, which could cause the problem. But weirdly, I checked the MD5 and the value is the same. 
Anyway, I'm trying to figure out how I can remove those characters.

**Comment by Yufei-Yan** [comment]
Solved the problem with the command at [stackoverflow](https://stackoverflow.com/questions/1068650/using-awk-to-remove-the-byte-order-mark). 
Issue closed. 
Thank you all.

**Comment by DavidKelleySCSC** [comment]
Sounds good to me.  I think when we use the Qt editor the same thing occurs here.    
For the record, the MD5 hash for the official SAE J2735 ASN is as follows

> For
> J2735_201603_ASN.asn
> 
> the MD5 sum is:
> d0db3a05b2f1204a7dbcaa1bc54c78ec
> 
> the file is dated March 7th 2016

**Comment by brchiu** [comment]
hi @DavidKelleySCSC ,

I guess you are checking the standalone version of SAE J2735 ASN file.

However, I purchased SAE J2735 specification and ASN file from SAE's website. 
Then I was granted to download J2735SET_201603.zip.
After unzip it, there are three files inside it : 
`J2735_201603DA.ASN`,  `J2735_201603.pdf` and  `MD5checkSum.txt`

The J2735_201603DA.ASN inside J2735SET_201603.zip has MD5 hash :
```
$ md5sum J2735_201603DA.ASN 
301f4691cd5429130f84f16b4ddd933f  J2735_201603DA.ASN
```

This MD5 hash is the same as indicated in hMD5checkSum.txt of J2735SET_201603.zip.
```
The MD5 checksum of the file J2735_201603DA.ASN is:
301f4691cd5429130f84f16b4ddd933f
```

It is **this** ASN file has BOM characters at beginning of it.

**Comment by DavidKelleySCSC** [comment]
What I was checking against was the final package I had sent to SAE as part of the pubs process.   This is quite odd to me, but I will investigate with the SAE staff and try to get to the bottom of it.  As you state, the master zip file has three parts, the final PDF of the J2735 standard, the ASN in what should be a ASCII format file (with the *.AND file type), and a text file stating the MD5 check.  Those Aug date/times are odd as well.  To recap; the BOM symbol should not be there and the MD5 hash should match to confirm that it is an authoritative copy from SAE.

**Comment by DavidKelleySCSC** [comment]
I had posted the wrong hash in the above (it was from a pre release), and all that **brchiu** states is correct and now re-validated.  Cutting to the end, there is in fact a 3 octet BOM at the start of the file and the MD5 matches to that being present.    SAE staff provided a "pristine" copy and we worked it out this morning.   Here is a preview of some draft text on how to determine this for others.  

**How to confirm you have the unmodified ASN for SAE for J2735_201603**
First, it is delivered to the purchaser as a zip file that contains the ASN as well as the 267 page PDF of the standard itself.  As per SAE rules, you are allowed to use this copyrighted material to freely create various derivative products, but may not give the ASN or the standard itself away to other parties. 

The zip file contains a folder named "**J2735SET_201603**" and inside that you will find three files as follows.  Note the sizes and dates.
![asn_pdf_files_package](https://user-images.githubusercontent.com/5143060/28334886-678b9fbc-6bb1-11e7-9821-a4ac85b4aa1a.png)


Here we consider the ASN specification which is found in the file **J2735_201603DA.ASN** which is itself simply a text file of precisely  223,411 bytes in length.  The file starts with the following few lines:

```
> -- Product Code: J2735ASN-201603 (also available
> -- as a set with J2735-201603 Standard)
> 
> -- SAE J735-201603 Final ASN spec
> --
> --
> -- This product is provided by SAE to purchasers
> -- as SAE J2735ASN-201603 (tm) as a companion product to
> -- assist them in deployment of SAE Standard J2735-201603.
> -- This document, like SAE J2735(tm) itself contains
> -- material copyrighted by SAE International.
```

The file **MD5checkSum.txt** in the above folder contains the contents of:

> The MD5 checksum of the file J2735_201603DA.ASN is:
> 301f4691cd5429130f84f16b4ddd933f

**Note** that an MD5 hash is not case sensitive, so this value is also valid: 301F4691CD5429130F84F16B4DDD933F

If you create an MD5 hash on the file, and it is unedited, you should be able to obtain the same hash value.  Any other value indicates that the file has been edited or changed in some way.

**Byte Order Mark (BOM)**
The file, as it is shipped from SAE, does contain an initial BOM character (found in the first three bytes). This can be problematic for some ASN.1 tools to process and in these cases needs to be removed.   The file starts with the octet sequence:  `0x ef bb bf 2d 2d 20 50 72 6f 64 75 63 74`   (where 0xEFBBBF is the the BOM and indicates UTF-8). 

You can remove this with a wide variety of editor tools  (I happened to use Notepad++ and the Hex plug in).  Of course, cannot speak for all the various 3rd party tool makers, but the two Commercial Vendors we use here did not have issues consuming this ASN.  We no longer are able to use ASN1c tool for this code due to the issues with UPER, OIDs and macros now found in J2935.  But those of you who know me know I really want this group and VLM to be able to improve the tool so it can be used for this work once again
