### ISSUE TITLE
check-REAL test fails on ppc64le architecture with Ubuntu/Debian

### ISSUE THREAD

**Issue by rgdoliveira** [vlm/asn1c#179]
I tried asn1c build on ppc64le architecture (both on Ubuntu and Debian) and it worked fine. However when I run make check, the test check-REAL fails with the following error (taken from check-REAL.log file):

Line 674: double value 1797693134862315708145274237317043567980705675258449965989174768031572607800285387605895586327668781715404589535143824642343213268894641827684675467035375169860499105765512820762454900903893289440758685084check-REAL: check-REAL.c:58: check_str_representation: Assertion '!strcmp(s0, sample)' failed.
55133942304583236903222948050016458515597071187135716751514538302097059854097235942464302912735919891897.119539993272 [ffffffffffffef7f] (ilogb 1023)
frexp(1.000000, 1024): [ffffffffffffef3f]
converted into [8103cb1fffffffffffff]: 10
and back to double: [ffffffffffffef7f] (ilogb 1023)
179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948050016458515597071187135716751514538302097059854097235942464302912735919891897.119539993272 vs 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948050016458515597071187135716751514538302097059854097235942464302912735919891897.119539993272
OK
674: Checking 1.79769e+308->["179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948050016458515597071187135716751514538302097059854097235942464302912735919891897.11953999327206"] against ["179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0"] (canonical follows...)
FAIL check-REAL (exit status: 134)

The assert(!strcmp(s0, sample)) from check_str_representation() function failed.

**Comment by RFDonovan** [comment]
Hi ,
 have you tried to go directly without check?

**Comment by theirix** [comment]
Hello.
I'm working for the fix for downstream issue. I've tried to reproduced it on amd64 using various compilers, operating systems and address sanitizer. It can be only seen on ppc64el and it significantly complicates debugging (by the way, using asan helps to find a bug #188).

I found a little strange that at ppc64el a following string
```
Line 675: double value 1797693134862315708145274237317043567980705675258449965989174768031572607800285387605895586327668781715404589535143824642343213268894641827
684675467035375169860499105765512820762454900903893289440758685084551339423045832369032229480500164585155970711871357167515145383020970598540972359424643029127359
19891897.119539993272 [ffffffffffffef7f] (ilogb 1023)
```

is printed in check_REAL.c check_impl:
```c
    printf("Line %d: double value %.12f [", lineno, orig_dbl);
```

So it was related to ppc64 interpretation of DBL_MAX. It's `179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948050016458515597071187135716751514538302097059854097235942464302912735919891897.119539993272` with 14 trailing points.
So the test `check(&rn, DBL_MAX, "179769313 ... .0", "1.79  7693134862316E308")` obviously failed. 

Now the test cannot be easily fixed and should be excluded. Naïve fix
```c
sprintf(buf_dblmax, "%f", DBL_MAX);
check(&rn, DBL_MAX, buf_dblmax, "1.79  7693134862316E308")`
``` does not work because libc prints 14 digits after the point while asn1c prints only one zero digit via REAL__dump. Maybe the special kind of `check` must be written for handling DBL_MAX?

**Comment by rgdoliveira** [comment]
@theirix Thanks for fixing it downstream in Debian.  
I also could only reproduce it in ppc64le and with newer versions of gcc, so I opened a bug to IBM compiler team (that works with ppc64le)

As it does not seems a bug in asn1c, I'm closing it.

**Comment by rgdoliveira** [comment]
Just to add extra info about this issue...

A bug was reported at [glibc](https://sourceware.org/bugzilla/show_bug.cgi?id=22142) and a [patch](https://patchwork.sourceware.org/patch/22896/) was submitted to fix this issue on ppc64le.

**Comment by theirix** [comment]
Thanks, waiting for patches entering Debian.
