### ISSUE TITLE
SEQUENCE OF/SET OF generate infinite loop in constraint check

### ISSUE THREAD

**Issue by pzb** [vlm/asn1c#195]
https://github.com/vlm/asn1c/blame/master/libasn1compiler/asn1c_constraint.c#L214 generates a call to the function calling it.  This creates an infinite loop.

An example is the SubjectAltName in the PKIX1 sample.

**Comment by pzb** [comment]
I'm guessing `SubjectAltName_1_inherit_TYPE_descriptor(td)` needs to be called in the _constraint method in a manner similar to how it is called in _free, _print, etc.

**Comment by sleevi** [comment]
@vlm The correct call would seem to be td->op->check_constraints, so that it nests into the `asn_OP_SEQUENCE_OF` or `asn_OP_SET_OF` constraint (the underlying type checker, `SEQUENCE_OF_constraint` / `SET_OF_constraint`, which would then fall to the `asn_MBR_*` definition for member checking). This may be a regression from https://github.com/vlm/asn1c/commit/1f87ac0058bdf5345cc8dff5d98df09405e3dd2c ?

**Comment by brchiu** [comment]
hi, All, 

I check-out the commit 6bc7a11d9e76d2b6116b5e23a21800d028c98d08  (the one before merging [Simplify the logic of accessing codec function for specific TYPE](https://github.com/vlm/asn1c/commit/1fa31c9e3e4182251439e8d5795fe4abf73f3152) , ya, again, it's my PR) 

The excerpt of generated `SubjectAltName.c` is 
```

int
SubjectAltName_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using GeneralNames,
 * so here we adjust the DEF accordingly.
 */
static void
SubjectAltName_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_GeneralNames.free_struct;
	td->print_struct   = asn_DEF_GeneralNames.print_struct;
	td->check_constraints = asn_DEF_GeneralNames.check_constraints;
	td->ber_decoder    = asn_DEF_GeneralNames.ber_decoder;
	td->der_encoder    = asn_DEF_GeneralNames.der_encoder;
	td->xer_decoder    = asn_DEF_GeneralNames.xer_decoder;
	td->xer_encoder    = asn_DEF_GeneralNames.xer_encoder;
	td->uper_decoder   = asn_DEF_GeneralNames.uper_decoder;
	td->uper_encoder   = asn_DEF_GeneralNames.uper_encoder;
	td->oer_decoder    = asn_DEF_GeneralNames.oer_decoder;
	td->oer_encoder    = asn_DEF_GeneralNames.oer_encoder;
	if(!td->oer_constraints)
		td->oer_constraints = asn_DEF_GeneralNames.oer_constraints;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_GeneralNames.per_constraints;
	td->elements       = asn_DEF_GeneralNames.elements;
	td->elements_count = asn_DEF_GeneralNames.elements_count;
	td->specifics      = asn_DEF_GeneralNames.specifics;
}

asn_TYPE_descriptor_t asn_DEF_SubjectAltName = {
	"SubjectAltName",
	"SubjectAltName",
	SubjectAltName_free,
	SubjectAltName_print,
	SubjectAltName_constraint,
	SubjectAltName_decode_ber,
	SubjectAltName_encode_der,
	SubjectAltName_decode_xer,
	SubjectAltName_encode_xer,
	0, 0,	/* No OER support, use "-gen-OER" to enable */
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SubjectAltName_tags_1,
	sizeof(asn_DEF_SubjectAltName_tags_1)
		/sizeof(asn_DEF_SubjectAltName_tags_1[0]), /* 1 */
	asn_DEF_SubjectAltName_tags_1,	/* Same as above */
	sizeof(asn_DEF_SubjectAltName_tags_1)
		/sizeof(asn_DEF_SubjectAltName_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	0	/* No specifics */
};
```
So, if `SubjectAltName_1_inherit_TYPE_descriptor()` was called before `SubjectAltName_constraint()` being called, indirectly through other functions like `SubjectAltName_decode_ber()` ... . Then function pointed by the content of `asn_DEF_GeneralNames.check_constraints` will be called.

However, if `SubjectAltName_1_inherit_TYPE_descriptor()` has never been called yet, there will still be a loop.

As for @sleevi  suggested to change it as `td->op->check_constraints`, it is a safe way and we only need to change line 3121 of `asn1c_C.c`
```
	if(asn1c_emit_constraint_checking_code(&tmp_arg) == 1) {
		OUT("return td->check_constraints"
			"(td, sptr, ctfailcb, app_key);\n");
	}
to
	if(asn1c_emit_constraint_checking_code(&tmp_arg) == 1) {
		OUT("return td->op->check_constraints"
			"(td, sptr, ctfailcb, app_key);\n");
	}
```
I knew this code segment but left it without changing to `td->op->check_constraints`, compared to line 1419 to 1424 of `asn1c_C.c` , because I thought there might be `child TYPE` specific check_constraint rather than all route to `parent TYPE` specific check_constraint. 

Perhaps my understanding or approach was wrong. 

Any further refinement is welcomed.

**Comment by sleevi** [comment]
@brchiu Thanks for looking at this! I'm not fully sure I parse your reply with the `parent TYPE` vs `child TYPE` concern, but let me try to restate it and see if you agree with me that:

* Changing https://github.com/vlm/asn1c/blob/290b4d6918fe567c412fee2cf139fc82e442ee26/libasn1compiler/asn1c_C.c#L3123 to call `td->op->check_constraints` is **not** correct
* Changing https://github.com/vlm/asn1c/blob/290b4d6918fe567c412fee2cf139fc82e442ee26/libasn1compiler/asn1c_constraint.c#L214 to call `td->op_check_constraints` **is** correct

That is, as I read it, for https://github.com/vlm/asn1c/blob/290b4d6918fe567c412fee2cf139fc82e442ee26/libasn1compiler/asn1c_C.c#L1417 to be true, there must be no derived/combined constraints - that is, the only place the retval = 1 is https://github.com/vlm/asn1c/blob/290b4d6918fe567c412fee2cf139fc82e442ee26/libasn1compiler/asn1c_constraint.c#L42

So we know `asn1c_emit_constraint_checking_code` will have emitted constraints (including for `SET OF`/`SEQUENCE OF` size constraints) as appropriate. Additionally, we know that we're in a `SEQUENCE OF`/`SET OF` construct, because it's explicit ( https://github.com/vlm/asn1c/blob/290b4d6918fe567c412fee2cf139fc82e442ee26/libasn1compiler/asn1c_constraint.c#L211 )

So if we have a definition, such as
```
SubjectAltName ::= GeneralNames
GeneralNames ::= SEQUENCE SIZE (1..MAX) of GeneralName
GeneralName ::= CHOICE ...
```

Then we know that SubjectAltName is just an alias for GeneralNames. The current generator code expands that alias inline - as evidenced by generating `SubjectAltName_constraint` and `IssuerAltName_constraint`. That is, it expands the `GeneralNames` constraint (the size limit) into the `SubjectAltName_constraint` / `IssuerAltName_constraint` functions (rather than a common `GeneralNames_constraint`, which you would logically expect - meaning that the enforcement code for the size >= 1 is duplicated across both of the SAN/IAN, despite the common `parent TYPE`)

So I think it's safe:
  * because the size limit is expanded into `SubjectAltName_constraint` and `IssuerAltName_constraint`, meaning there's not an underlying size limit check in the `GeneralNames_constraint` (or, put differently, all of the `parent TYPE`s constraints have been expanded into the `child TYPE`'s constraint check
  * because we and because we know we're in a `SEQUENCE_OF` / `SET_OF` (because of https://github.com/vlm/asn1c/blob/290b4d6918fe567c412fee2cf139fc82e442ee26/libasn1compiler/asn1c_constraint.c#L211 )
    * and we know that either a `SEQUENCE_OF` or a `SET_OF` will reference `asn_MBR_%s_%d` (because of https://github.com/vlm/asn1c/blob/290b4d6918fe567c412fee2cf139fc82e442ee26/libasn1compiler/asn1c_C.c#L3279 ) in the `td->elements` (with a `td->elements_count` of 1),
    * and we know that, because it's a `SEQUENCE_OF`/`SET_OF` we'll reference `&asn_OP_SEQUENCE_OF` or `&asn_OP_SET_OF` (as part of the logic in https://github.com/vlm/asn1c/blob/290b4d6918fe567c412fee2cf139fc82e442ee26/libasn1compiler/asn1c_C.c#L3178-#L3215 ), 
    * and we know that a SET_OF_constraint will pull from the `memb_constraints` of `td->elements` in https://github.com/vlm/asn1c/blob/290b4d6918fe567c412fee2cf139fc82e442ee26/skeletons/constr_SET_OF.c#L848 (aka `asn_MBR_%s_%d` from above)

Then the full constraint checking path of `SubjectAltName` (implicitly `GeneralNames`, by virtue of the code duplication) -> `GeneralName` will be observed.

All of this logic only applies for `SET_OF` / `SEQUENCE_OF` constraints - because for those (and those only), 'parent' types (like `GeneralNames`) will have their constraint checking logic duplicated/uplifted into their child types (`SubjectAltName`), so having the call to `td->op->check_constraints` is fine and correct (since op == `&asn_OP_SEQUENCE_OF` for both the parent and child types)

Does that sound correct?

**Comment by pzb** [comment]
I changed https://github.com/vlm/asn1c/blob/cf3f6ebb9fe20152d93fe39d0065bc2feb576c23/libasn1compiler/asn1c_constraint.c#L214 to `td->op->check_constraints` and tested locally.  It solves the loop problem.

**Comment by vlm** [comment]
Fixed, thank you!
