### ISSUE TITLE
UniversalString with uper encoder has bugs in 0.9.28 - last characters are lost by encoder.

### ISSUE THREAD

**Issue by lykkja** [vlm/asn1c#199]
I have the following test program:

const char *pTest = "This is a text string.";
IA5String_t ia5;
memset(&ia5, 0, sizeof(ia5));
OCTET_STRING_fromBuf(&ia5, pTest, -1);

char buffer[512];
asn_enc_rval_t enc = uper_encode_to_buffer(&asn_DEF_UniversalString, &ia5, buffer, sizeof(buffer));
printf("len=%d bits,  %d bytes: ", (int)enc.encoded, (int)(enc.encoded+7)/8);
for (int d=0; d<(enc.encoded+7)/8; d++)
      printf(" %02x", buffer[d] & 0xff);
printf("\n");
 IA5String_t *dec = 0;
asn_dec_rval_t rval = uper_decode(0, &asn_DEF_UniversalString, (void **)&dec, buffer, (enc.encoded+7)/8, 0, 0);
printf("consumed: %d\n", (int)rval.consumed);
printf("back: %s\n", dec->buf);

This prints:
len=168 bits,  21 bytes:  05 54 68 69 73 20 69 73 20 61 20 74 65 78 74 20 73 74 72 69 6e
consumed: 168
back: This is a text strin

The last two characters are missing.

**Comment by vlm** [comment]
This code happens to violate the implicit UniversalString constraint, in which the length of it should be modulo 4.

See the commit https://github.com/vlm/asn1c/commit/4ef01a249dc92c670528016768947c88d5eb382e which outright prohibits encoding such strings.

P.S. Please use UniversalString_t instead of IA5String_t.

**Comment by lykkja** [comment]
Thank you for the very quick followup and advice!
