### ISSUE TITLE
Can't Compile External sequences

### ISSUE THREAD

**Issue by ddreyer** [vlm/asn1c#296]
When I compile the following:

```My-Schema DEFINITIONS ::=
BEGIN

  MyObject ::= EXTERNAL

  SomeObject ::= SEQUENCE {
    body SEQUENCE OF MyObject
  }

END
```

The SEQUENCE member of `SomeObject_t`, `body`, compiles as `A_SEQUENCE_OF(struct MyObject) list`, where `MyObject` is forward declared but never declared anywhere else. It seems like it should compile to `A_SEQUENCE_OF(struct MyObject_t) list`. Is this supposed to occur?

**Comment by velichkov** [comment]
Hi @ddreyer,

> It seems like it should compile to A_SEQUENCE_OF(struct MyObject_t) list. Is this supposed to occur?

I agree that this could be improved but also it should work as is because this type is used only to define a pointer.

Also note that it is not directly related to the EXTERNAL and you could reproduce it with any other SEQUENCE (and probably with other types as well)
```asn1
My-Schema DEFINITIONS ::=

BEGIN

MySequence ::= SEQUENCE {
	...
}

MyObject ::= MySequence -- EXTERNAL

SomeObject ::= SEQUENCE {
	body SEQUENCE OF MyObject
}

END
```
SomeObject.h
```c
/* SomeObject */
typedef struct SomeObject {
	struct body {
		A_SEQUENCE_OF(struct MyObject) list;
```
MyObject.h
```
/* MyObject */
typedef MySequence_t	 MyObject_t;
```

The code that emits the type name in `A_SEQUENCE_OF(...)` is  https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/libasn1compiler/asn1c_C.c#L841-L843

**Comment by ddreyer** [comment]
Understood, it just threw me off a bit because I was expecting a `MyObject_t` pointer rather than a `MyObject` pointer. 

Also I forgot to mention that I am using this version: https://github.com/vlm/asn1c/pull/295#issue-214795371
