### ISSUE TITLE
Example from asn1c-usage.pdf doesn't work.

### ISSUE THREAD

**Issue by xfbs** [vlm/asn1c#345]
I'm using asn1c version 0.9.28 on macOS.

The example calls for running:

```bash
asn1c -no-gen-example rectangle.asn
```

But when I do so, I'm greeted with the help text, instead of getting something compiled.

**Comment by velichkov** [comment]
Hi @xfbs,

> I'm using asn1c version 0.9.28 on macOS.
> 
> The example calls for running:
> 
> ```shell
> asn1c -no-gen-example rectangle.asn
> ```
> 
> But when I do so, I'm greeted with the help text, instead of getting something compiled.

Most probably you are reading the manual `asn1c-usage.pdf` downloaded from the `master` branch while you are using the older version `0.9.28` where the ` -no-gen-example` option is not available.

In the [asn1c-usage.pdf from v0.9.28 tag](https://github.com/vlm/asn1c/raw/v0.9.28/doc/asn1c-usage.pdf) this example is without  ` -no-gen-example` as its not present there.

Is there any particular reason to use `v0.9.28` instead of current `master`?

**Comment by xfbs** [comment]
Ah! That makes sense. Yeah, I cloned the repo for the documentation — but I'm using the asn1c 0.9.28 from Homebrew. Managed to got it working regardless!
