### ISSUE TITLE
/usr/bin/ld: converter-sample.o:(.data.rel+0x0): undefined reference to `asn_DEF_PDU'

### ISSUE THREAD

**Issue by chetanpandey1266** [vlm/asn1c#483]
I am getting this when I am trying to run Makefile in ubuntu

There is comment related to this in `converter-sample.c` but I couldn't understand it

```cpp
/* Convert "Type" defined by -DPDU into "asn_DEF_Type" */
```

**Comment by kentkost** [comment]
PDU is usually the the top most object you want to decode.

By setting the -DPDU option then the converter-sample will via. macros set the PDU you want to decode. Otherwise you would have to program it yourself manually.

Look at the [quickstart example](http://lionet.info/asn1c/asn1c-quick.pdf)

You could for example have a grammar like this:

```
TestModule DEFINITIONS ::= BEGIN 
    
    Circle ::= SEQUENCE { 
        position-x INTEGER, 
        position-y INTEGER, 
        radius INTEGER (0..MAX) 
    }
    
    Rectangle::= SEQUENCE { 
        length INTEGER, 
        width INTEGER
    }
     
END 
```

Because this effectively have two PDUs to choose from you could make two different converters from it like so

`gcc -DPDU=Circle -I. -o CircleDecoder.exe *.c`
and
`gcc -DPDU=Rectangle -I. -o RectangleDecoder.exe *.c`

In order to better understand the preprocessors in converter-example.
You can try passing `-E` to gcc as you compile. This will generate a `.i` file that shows the value after preprocessing.

**Comment by chetanpandey1266** [comment]
Hey I tried this and I am getting the decoder. Now the decoder takes an argument `iber` which is what I understand is the ber encoded data. Now I have a ber encoded string which I want to decode, how should I pass it to the decoder? I tried passing it directly but that didn't worked.

**Comment by kentkost** [comment]
There are multiple ways to do this. Again read the [quickstart example](http://lionet.info/asn1c/asn1c-quick.pdf)
And there is also the [documentation](https://lionet.info/asn1c/asn1c-usage.pdf).
It is hard to help when I can't see the code. And i don't know what you want to decode it to.

Long code short.

```C
char buf[1024]; /* Temporary buffer */
asn_dec_rval_t rval; /* Decoder return value */
Circle_t *circle = 0; /* Type to decode. Note this 0! */
FILE *fp; /* Input file handler */
size_t size; /* Number of bytes read */
char *filename="E:\\path\\to\\der\\data.der"; /* Input file name */

/* Open input file as read-only binary */
fp = fopen(filename, "rb");
if(!fp) {
    perror(filename);
    exit(1);
}

/* Read up to the buffer size */
size = fread(buf, 1, sizeof(buf), fp);
fclose(fp);

if(!size) {
    fprintf(stderr, "%s: Empty or broken\n", filename);
    exit(1);
}

/* Decode the input buffer as circle type */
rval = ber_decode(0, &asn_DEF_Circle, (void **)&circle, buf, size);

if(rval.code != RC_OK) {
    fprintf(stderr, "%s: Broken Circle encoding at byte %ld\n", filename, (long)rval.consumed);
    exit(1);
}

/*Encode to whatever you want into a buffer*/
// choose what output should be
enum asn_transfer_syntax osyntax = ATS_BASIC_XER;
asn_TYPE_descriptor_t *pduType = &asn_DEF_Circle;
asn_encode_to_new_buffer_result_t res = asn_encode_to_new_buffer(NULL, osyntax, pdutype, circle);

```
