### ISSUE TITLE
Incorrect DER output

### ISSUE THREAD

**Issue by pzb** [vlm/asn1c#79]
`echo 'MAMBAQA=' | base64 -d | certlint-x509helper -p BasicConstraints -oder - | openssl asn1parse -inform DER`

The structure is defined as

``` text
BasicConstraints ::= SEQUENCE {
     cA                      BOOLEAN DEFAULT FALSE,
     pathLenConstraint       INTEGER (0..MAX) OPTIONAL }
```

According to DER

> 11.5 Set and sequence components with default value
> The encoding of a set value or sequence value shall not include an encoding for any component value which is equal to its default value.

What is observed is that the DER output contains false, which is the default value. The output in this example should be an empty sequence.

**Comment by sleevi** [comment]
@vlm - This looks like an easy fix, as the SEQUENCE skeleton for uper already appears to handle this logic, since it has to handle the presence bitmap & encoding.

It looks like if https://github.com/vlm/asn1c/blob/6b949bbd7ae00081a510622016f16eaa2b3b48f1/skeletons/constr_SEQUENCE.c#L1376-L1394 was uplifted to https://github.com/vlm/asn1c/blob/6b949bbd7ae00081a510622016f16eaa2b3b48f1/skeletons/constr_SEQUENCE.c#L530-L539 and to https://github.com/vlm/asn1c/blob/6b949bbd7ae00081a510622016f16eaa2b3b48f1/skeletons/constr_SEQUENCE.c#L569-L574 this would address @pzb 's issue

(Unfortunately, I cannot contribute that patch myself)

**Comment by sleevi** [comment]
@vlm Turns out it was messier than I realized - for BOOLEANS with DEFAULT values (ATV_TRUE, ATV_FALSE as literals), no default function was being associated at all. This would also affect cases of PER/XER.

I created https://github.com/vlm/asn1c/pull/181 to try and fix this, with tests. I'm not terribly thrilled with the tests, but they do highlight the issue and cover both SEQUENCEs and SETs. Could you take a look?

**Comment by vlm** [comment]
Merged, thank you!

@sleevi if you don't mind me asking, I am curious why couldn't you create a patch yourself and then ended up creating it anyway?

**Comment by sleevi** [comment]
@vlm I had initially hoped it'd be more expedient to highlight the bug (from casual reading). When @pzb pointed out it'd been open for over a year and a half, I decided it was worth the hassle to go through our internal open-source licensing process if it would help get it merged :)
